blogku2/config/routes.rb
Rails.application.routes.draw do
  resources :posts do 
  	resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  root to: "posts#index"

  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'
end

blogku2/app/models/admin.rb
class Admin < ActiveRecord::Base
	before_save { self.email = email.downcase }

	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }

	VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL }, uniqueness: {case_sensitive: false}

	has_secure_password
	validates :password, length: { minimum: 6 }

	def Admin.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def Admin.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private 
		def create_remember_token
			self.remember_token = Admin.encrypt(Admin.new_remember_token)
		end

end

blogku2/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

blogku2/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

   	validates :title, presence: true, length: {maximum: 60}
   	validates :body, presence: true
end

blogku2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

end

blogku2/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:author, :body))

		redirect_to post_path(@post)
	end
end

blogku2/app/controllers/posts_controller.rb
#app/controllers/posts_controller.rb

class PostsController < ApplicationController
	before_action :signed_in_admin, only: [:new, :create]

	def index
		@posts =Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
	end

	def new
		
	end

	def create
		@post = Post.new(post_params)

		respond_to do |format|
			if @post.save
				flash[:success] = 'Article was successfully created.'
				format.html { redirect_to posts_path }
			else
				flash[:danger]  = 'There was a problem creating the article.'
				format.html { render :new }
			end
		end
	end

	def update
		@post = Post.find(params[:id])
		respond_to do |format|
			if @post.update_attributes(post_params)
				flash[:success] = 'Article was successfully updated.'
				format.html { redirect_to posts_path }
			else
				flash[:danger] = 'There was a problem updating the Article.'
				format.html { render :edit }
			end
		end
	end

	def destroy
		Post.find(params[:id]).destroy
		respond_to do |format|
			flash[:success] = 'Article was successfully destroyed.'
			format.html { redirect_to posts_path }
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	private 
	def post_params
		params.require(:post).permit(:title, :body)
	end

	#Before filters
	def signed_in_admin
		unless admin?
			store_location
			redirect_to signin_url, notice: 'Area Khusus Admin'
		end
		
	end

end

blogku2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
<<<<<<< HEAD
=======

	def new
		
	end

	def create
		admin = Admin.find_by(email: params[:session][:email].downcase)
		if admin && admin.authenticate(params[:session][:password])
			sign_in admin 
			redirect_back_or root_url
		else
			if admin 
				message = 'password Salah Men.'
			else
				message = 'Email tidak terdaftar.'
			end
			flash[:danger] = message

			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
>>>>>>> 38396a90dc3d58d5a9776e8678d948406393b43a
end

blogku2/app/helpers/comments_helper.rb
module CommentsHelper
end

blogku2/app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(admin)
		remember_token = Admin.new_remember_token

		cookies.permanent[:remember_token] = remember_token

		admin.update_attribute(:remember_token, Admin.encrypt(remember_token))

		self.current_admin = admin
	end

	def current_admin=(admin)
		@current_admin = admin
	end

	def current_admin
		remember_token = Admin.encrypt(cookies[:remember_token])
		@current_admin ||= Admin.find_by(remember_token: remember_token)
	end

	def admin?
		!current_admin.nil?
	end

	def sign_out
		self.current_admin = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

end

blogku2/app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
      	<img src="" alt="Brand">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
        	<%= link_to 'Home', root_url %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<% if !admin? %>
        <li>
        	<%= link_to 'Admin', signin_url %>
        </li>
        <% else %>
        <li>
        	<%= link_to 'Logout', signout_url, method: 'delete' %>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

blogku2/app/views/shared/_sidebar.html.erb
<!-- app/views/shared/_sidebar.html.erb -->

<section class="sidebar">

  <!-- Sidebar user panel (optional) -->
  <div class="user-panel">
    <div class="pull-left image">
      <img src="<%= image_url('user2-160x160.jpg') %>" class="img-circle" alt="User Image" />
    </div>
    <div class="pull-left info">
      <p>Alexander Pierce</p>
      <!-- Status -->
      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
  </div>

  <!-- search form (Optional) -->
  <form action="#" method="get" class="sidebar-form">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Search..."/>
      <span class="input-group-btn">
        <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
      </span>
    </div>
  </form>
  <!-- /.search form -->

  <!-- Sidebar Menu -->
  <ul class="sidebar-menu">
    <li class="header">HEADER</li>
    <!-- Optionally, you can add icons to the links -->
    <li class="active"><a href="#"><i class='fa fa-link'></i> <span>Link</span></a></li>
    <li><a href="#"><i class='fa fa-link'></i> <span>Another Link</span></a></li>
    <li class="treeview">
      <a href="#"><i class='fa fa-link'></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
      <ul class="treeview-menu">
        <li><a href="#">Link in level 2</a></li>
        <li><a href="#">Link in level 2</a></li>
      </ul>
    </li>
  </ul><!-- /.sidebar-menu -->
</section>
<!-- /.sidebar -->